### PR TITLE
Add marked support.

### PR DESCRIPTION
**Pull request by bdgong**

### CODE REVIEW

**Comment by mzlogin** [comment]
Great, thx for your PR.

**Comment by mzlogin** [comment]
In addition, would you please add some test cases for Marked to file test/test.vim when you are free? Thanks a lot!

**Comment by bdgong** [comment]
Sure, of course.  But before do that, I wanna read the source code of markdown-preview and marked at first, just give me some time

**Comment by mzlogin** [comment]
OK. Just take your time.

**Pull request merged**
